[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
decorations = "none" # Removes the window decoration (title bar, etc.)

[scrolling]
history = 100_000

[font]
size = 14

normal = { family = "Aporetic Sans Mono", style = "Regular" }
bold = { family = "Aporetic Sans Mono", style = "Bold" }
italic = { family = "Aporetic Sans Mono", style = "Italic" }
bold_italic = { family = "Aporetic Sans Mono", style = "Bold Italic" }

# normal = { family = "Victor Mono", style = "Regular" }
# bold = { family = "Victor Mono", style = "Bold" }
# italic = { family = "Victor Mono", style = "Italic" }
# bold_italic = { family = "Victor Mono", style = "Bold Italic" }

offset = { y = 20 }
glyph_offset = { y = 20 }

[colors]
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'
