# Misc
adjust_line_height 	      160%
cursor_blink_interval 	  0
window_padding_width 	  10
hide_window_decorations   titlebar-only
enable_audio_bell 	      no
macos_option_as_alt       left
term                      xterm-kitty
scrollback_lines          100000
touch_scroll_multiplier   2.0
copy_on_select            yes
mouse_hide_wait           -1
allow_remote_control      yes
listen_on                 unix:/tmp/kitty
editor                    nvim
shell_integration         no-sudo
shell_integration         no-title
shell                     zsh --login
confirm_os_window_close   0

# Key Mappings
clear_all_shortcuts yes

# Use cmd on macOS as modifier
kitty_mod super

# Config
map kitty_mod+shift+e open_config_file
map kitty_mod+shift+r load_config_file

# Copy/paste
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+p paste_from_buffer

# Windows
map kitty_mod+enter launch --location=split --cwd=current
map kitty_mod+shift+s launch --location=vsplit --cwd=current
map kitty_mod+shift+v launch --location=hsplit --cwd=current
map kitty_mod+d close_window

map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down

map kitty_mod+shift+h move_window left
map kitty_mod+shift+l move_window right
map kitty_mod+shift+k move_window up
map kitty_mod+shift+j move_window down

map kitty_mod+[ resize_window narrower
map kitty_mod+] resize_window wider
map kitty_mod+shift+[ resize_window taller
map kitty_mod+shift+] resize_window shorter 3
map kitty_mod+r resize_window reset
map kitty_mod+m maximize vertical

# Tabs
tab_bar_style             powerline
tab_powerline_style       angled
tab_title_template        "{title}"
tab_bar_filter            session:~ or session:^$
tab_bar_min_tabs          1

map kitty_mod+t combine : launch --cwd=current --type=tab --tab-title=" " : set_tab_title
map kitty_mod+w close_tab
map kitty_mod+, previous_tab
map kitty_mod+. next_tab
map kitty_mod+shift+. move_tab_forward
map kitty_mod+shift+, move_tab_backward
map kitty_mod+i set_tab_title

# Font
font_family		          Victor Mono Medium
bold_font        	      Victor Mono Bold
italic_font      	      Victor Mono Medium Oblique
bold_italic_font 	      Victor Mono Bold Oblique
font_size                 13
# Nerd Fonts v2.3.3
symbol_map                U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+E00A,U+E0A0-U+E0A3,U+E0B0-U+E0D4,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E6AA,U+E700-U+E7C5,U+EA60-U+EBEB,U+F000-U+F2E0,U+F300-U+F32F,U+F400-U+F4A9,U+F500-U+F8FF,U+F0001-U+F1AF0 Symbols Nerd Font Mono
disable_ligatures         cursor
# font_features             Iosevka +dlig cv94=3
spacing                   90

map kitty_mod+minus change_font_size current -1.0
map kitty_mod+equal change_font_size current +1.0

# Layout
enabled_layouts tall, stack
map kitty_mod+z next_layout
map kitty_mode+/ layout_action mirror toggle

# Misc
map kitty_mod+f launch --type=overlay zsh -c "~/.dotfiles/bin/kitty-sessionizer"
map kitty_mod+e goto_session ~/.dotfiles/kitty/sessions/dotfiles.kitty-session

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
