#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$$.tags" --fields=+aimlS --languages=php --PHP-kinds=+cf-va
mv "$$.tags" "tags"
